filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~

    json.keys_under_root: true
    json.add_error_key: true
    json.expand_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
